# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - master # Set this to the branch you want to trigger the deployment

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Build the project
#         # run: npm run build -- --output-path=dist/customer-matrix-app --base-href /customer-matrix-app/
#         run: ng build --prod --base-href "https://gabe19p.github.io/customer-matrix-app/"

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist/customer-matrix-app

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger deployment when pushing to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build the project
        run: ng build --prod --base-href "https://gabe19p.github.io/customer-matrix-app/"

      - name: Verify the build output
        run: ls -la ./dist/customer-matrix-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/customer-matrix-app
